<hr>

<table>
    <tr>
        <td>
            Generated by
            <strong>Commitment Corner</strong>
        </td>

        <td align="right">
            {{ now()->timezone('Asia/Jakarta')->format('d-m-Y H:i') }}
        </td>
    </tr>
</table>