<hr>

<table>
    <tr>
        <td>
            Generated by
            <strong>Commitment Corner</strong>
        </td>

        <td align="right">
            {{ now()->format('d M Y H:i') }}
        </td>
    </tr>
</table>